package com.adsprovider.jetpackcomposeonlineshopingproject1

import androidx.annotation.DrawableRes
//Madhav Aneraye 1
object Data {
    class Demo(
        @DrawableRes var img:Int,
        var name:String,
        var disp:String,
        var price:String
        )

    var dataList = listOf(
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),
        Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999"),Demo(R.drawable.image1,
            "Green Cut piece",
            "Green cut piece for tall and bright girl",
            "499"),
        Demo(R.drawable.image2,
            "Short Women Kurti",
            "Short Women Kurti for summer days and looks beautiful",
            "999")
    )
}